import type { ConsumerDefinition } from './module'

/**
 * Code generation for declarative consumers.
 *
 * `nats.consumers` in nuxt.config needs a bridge: the config is data, and
 * `defineNatsConsumer()` needs a real function reference. Resolving a handler path at
 * runtime is not an option in a bundled Nitro server, so the module emits a Nitro plugin
 * at build time that statically imports each handler and registers it.
 *
 * Kept as a pure string function, separate from module.ts, so the generated source can be
 * asserted in unit tests rather than only exercised through a full Nuxt build.
 */

/** Reject anything that would break out of the generated string literal. */
function assertSafeIdentifier(value: string, field: string, durable: string): void {
  if (value.includes('\'') || value.includes('\\') || value.includes('\n')) {
    throw new Error(
      `[nuxt-nats] Consumer "${durable}" has an unusable ${field}: quotes, backslashes and `
      + `newlines are not allowed.`,
    )
  }
}

export interface GenerateOptions {
  /**
   * Turns a ConsumerDefinition.handler into a module specifier the generated plugin can
   * import. Injected so tests do not need a Nuxt instance and so path resolution stays
   * the module's concern, not the generator's.
   */
  resolveHandler: (handler: string) => string
  /** Module specifier for defineNatsConsumer, resolved against the module's own runtime. */
  consumerUtilPath: string
}

/**
 * Build the source of the generated Nitro plugin.
 *
 * Throws rather than skipping on a malformed definition. A consumer that silently fails to
 * register is indistinguishable from a healthy one until the stream backs up, which is the
 * whole reason this option needed implementing rather than documenting.
 */
export function generateConsumerPlugin(
  consumers: ConsumerDefinition[],
  opts: GenerateOptions,
): string {
  const seen = new Set<string>()
  const imports: string[] = []
  const registrations: string[] = []

  consumers.forEach((c, i) => {
    if (!c.stream) throw new Error(`[nuxt-nats] Consumer at index ${i} is missing "stream".`)
    if (!c.durable) throw new Error(`[nuxt-nats] Consumer at index ${i} is missing "durable".`)
    if (!c.handler) {
      throw new Error(
        `[nuxt-nats] Consumer "${c.durable}" is missing "handler". Point it at a file that `
        + `default-exports an async (msg, payload) function, relative to server/.`,
      )
    }

    const key = `${c.stream}/${c.durable}`
    if (seen.has(key)) {
      throw new Error(
        `[nuxt-nats] Duplicate consumer "${c.durable}" on stream "${c.stream}". Two consumers `
        + `bound to one durable compete for the same messages.`,
      )
    }
    seen.add(key)

    assertSafeIdentifier(c.stream, 'stream', c.durable)
    assertSafeIdentifier(c.durable, 'durable', c.durable)
    if (c.deadLetterSubject) assertSafeIdentifier(c.deadLetterSubject, 'deadLetterSubject', c.durable)
    c.filterSubjects?.forEach(s => assertSafeIdentifier(s, 'filterSubjects', c.durable))

    const ident = `handler_${i}`
    imports.push(`import ${ident} from '${opts.resolveHandler(c.handler)}'`)

    const fields: string[] = [
      `stream: '${c.stream}'`,
      `durable: '${c.durable}'`,
    ]
    if (c.filterSubjects?.length) {
      fields.push(`filterSubjects: [${c.filterSubjects.map(s => `'${s}'`).join(', ')}]`)
    }
    if (c.ackPolicy) fields.push(`ackPolicy: '${c.ackPolicy}'`)
    if (typeof c.ackWait === 'number') fields.push(`ackWait: ${c.ackWait}`)
    if (typeof c.maxDeliver === 'number') fields.push(`maxDeliver: ${c.maxDeliver}`)
    if (c.backoff?.length) fields.push(`backoff: [${c.backoff.join(', ')}]`)
    if (c.deadLetterSubject) fields.push(`deadLetterSubject: '${c.deadLetterSubject}'`)
    if (c.provision) fields.push(`provision: '${c.provision}'`)
    fields.push(`handler: ${ident}`)

    registrations.push(`  defineNatsConsumer({\n    ${fields.join(',\n    ')},\n  })`)
  })

  return `// Generated by nuxt-nats. Do not edit.
//
// One Nitro plugin per build, registering every consumer declared in nuxt.config's
// \`nats.consumers\`. Handlers are imported statically so they survive bundling.
import { defineNitroPlugin } from 'nitropack/runtime'
import { defineNatsConsumer } from '${opts.consumerUtilPath}'
${imports.join('\n')}

export default defineNitroPlugin(() => {
${registrations.join('\n')}
})
`
}
